---
- name: Verificar temperatura de todas as capitais do Brasil
  hosts: localhost
  gather_facts: no

  vars:
    openweathermap_api_key: "your_api_key_here"

  tasks:
  - name: Obter temperatura das capitais do Brasil
    uri:
      url: "https://api.openweathermap.org/data/2.5/weather"
      method: GET
      return_content: yes
      params:
        q: "{{ item }},BR"
        appid: "{{ openweathermap_api_key }}"
        units: metric
    register: response
    loop:
    - "Rio Branco"
    - "Maceió"
    - "Macapá"
    - "Manaus"
    - "Salvador"
    - "Fortaleza"
    - "Brasília"
    - "Vitória"
    - "Goiânia"
    - "São Luís"
    - "Cuiabá"
    - "Campo Grande"
    - "Belo Horizonte"
    - "Belém"
    - "João Pessoa"
    - "Curitiba"
    - "Recife"
    - "Teresina"
    - "Rio de Janeiro"
    - "Natal"
    - "Porto Alegre"
    - "Porto Velho"
    - "Boa Vista"
    - "Florianópolis"
    - "São Paulo"
    - "Aracaju"
    - "Palmas"
  
  - name: Exibir temperatura das capitais do Brasil
    debug:
      msg: "{{ item.item }}: {{ item.json.main.temp }}°C"
    loop: "{{ response.results }}"

